name: Deploy DAB Bundle

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Which environment to deploy to? (dev, qa, prod)"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install PyYAML
        run: pip install pyyaml --upgrade

      - name: Install latest Databricks CLI (standalone binary)
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version
          databricks bundle --help

      - name: Generate dynamic databricks.yml with includes
        run: |
          python .github/workflows/scripts/generate_databricks_yml.py ${{ github.event.inputs.target }}

      # - name: Deploy DAB Bundle
      #   env:
      #       DATABRICKS_HOST: ${{ secrets['DATABRICKS_HOST_' + github.event.inputs.env | upper] }}
      #       DATABRICKS_TOKEN: ${{ secrets['DATABRICKS_TOKEN_' + github.event.inputs.env | upper] }}
      #   run: |
      #     databricks bundle deploy --target ${{ github.event.inputs.target }}
      
      - name: Deploy to dev
        if: ${{ github.event.inputs.target == 'dev' }}
        run: databricks bundle deploy --target dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV_LILLY }}
          # DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Deploy to qa
        if: ${{ github.event.inputs.target == 'qa' }}
        run: databricks bundle deploy --target qa
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_QA }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_QA }}
          
