name: Deploy DAB Bundle

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Which environment to deploy to? (dev, qa, prod)"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_HOST_DEV: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_HOST_QA: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_HOST_PROD: ${{ secrets.DATABRICKS_HOST_DEV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install PyYAML
        run: pip install pyyaml --upgrade

      - name: Install latest Databricks CLI (standalone binary)
        shell: bash
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version
          databricks bundle --help

      - name: Generate dynamic databricks.yml with includes
        run: |
          python .github/workflows/scripts/generate_databricks_yml.py ${{ github.event.inputs.target }}

      - name: Deploy DAB Bundle
        run: |
          databricks bundle deploy --target ${{ github.event.inputs.target }}
